version: 1.0.{build}
skip_tags: true
stack: redis, node 18
skip_commits:
  message: /\[chore\]/
branches:
  only:
  - master
  - /preview*/
  - /release*/
image: 
- Visual Studio 2022
environment:
  GH_TOKEN:
    secure: /o9VAhx5ewGmdLR9qcgFJMzBaCuzOmGlsXAHu7khUJLdQzsv4gJzLUfYDghcRPHd
  JAVA_HOME: C:\Program Files\Java\jdk19
  PATH: $(JAVA_HOME)\bin;$(PATH)
  dotnetsdk: 9.0.201
init:
    - cmd: git config --global core.autocrlf true
install:
    - ps: if ($isWindows) { Install-Product node '' }
    - cmd: pwsh .\dotnet-install.ps1 -Version %dotnetsdk% -InstallDir "C:\Program Files\dotnet"
    - ps: dotnet tool install --global GitVersion.Tool --ignore-failed-sources
    - ps: dotnet tool install --global dotnet-sonarscanner --ignore-failed-sources
    - ps: dotnet gitversion /l console /output buildserver
    - cmd: nuget install redis-64 -excludeversion
    - cmd: redis-64\tools\redis-server.exe --service-install
    - cmd: redis-64\tools\redis-server.exe --service-start
    - cmd: nuget install ReportGenerator -ExcludeVersion
    - ps: ./appveyorinit.ps1
build_script:
- ps: ./build.ps1
test_script:
- cmd: publish.cmd
artifacts:
    - path: artifacts/**/*.nupkg
      name: nuget    
deploy:
    - provider: NuGet
      api_key:
        secure: bvkKhXIKsDM1ThfcWTbuusND0sOBiDoJGOoD2fYijGoj4C9xx22QKfR7Y9q+j7eX
      on:
        branch: 
            - /preview*/
            - /release*/
        CI_WINDOWS: true
    - provider: GitHub
      auth_token: $(GH_TOKEN)
      draft: true
      prerelease: false
      release: $(Version)
      on:
        branch: 
            - /preview*/ 
        CI_WINDOWS: true
for:
-
  branches:
    only:
      - /release*/
  on_success:
      - cmd: semantic-release -b %APPVEYOR_REPO_BRANCH%
-
  branches:
    except:
      - master
