version: 1.0.{build}
skip_tags: true
branches:
  except:
  - gh-pages
image: 
- Visual Studio 2017
- Ubuntu
environment:
  access_token:
    secure: yQcU3EbE3/jaIhwn6e+n76xzcQ+tGXXdIZAmA3Z8ssj5IEYPehthJkLYhhNEmw21
init:
    - cmd: git config --global core.autocrlf true
install:
    - sh: nuget install GitVersion.CommandLine -ExcludeVersion
    - sh: mono GitVersion.CommandLine/tools GitVersion.exe /l console /output buildserver
    - cmd: gitversion /l console /output buildserver
    - cmd: nuget install redis-64 -excludeversion
    - cmd: redis-64\tools\redis-server.exe --service-install
    - cmd: redis-64\tools\redis-server.exe --service-start
    - cmd: nuget install JetBrains.dotCover.CommandLineTools -ExcludeVersion
    - cmd: nuget install ReportGenerator -ExcludeVersion
    - dotnet restore
build_script:
- cmd: build.cmd
- sh: powershell ./build-linux.ps1
test_script:
- cmd: publish.cmd
artifacts:
    - path: artifacts/**/*.nupkg
      name: nuget    
on_success:
    - cmd: git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - cmd: git config --global user.email "aguacongas@gmail.com"
    - cmd: git config --global user.name "Aguacongas"
    - cmd: git stash
    - cmd: git checkout gh-pages
    - cmd: IF EXIST latest ( rmdir /S /Q latest )
    - cmd: move coverage\docs latest
    - cmd: git add latest
    - cmd: git commit latest -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%"
    - cmd: git push
deploy:
    - provider: NuGet
      api_key:
        secure: 23wPDdRicGt2vZuJ8vd9TRBKmqjHkx5WjzZmKvyxd5j0fNPedjUScRTj/rT0ObJa
      on:
        branch: 
            - master
            - /release*/
    - provider: GitHub
      auth_token:
        secure: u7qaOQsrkLqq44yS24C0eM2vRCzp1A8gZTWNmlA58TIDJGmrDXguHL9H/vww7Fg/
      draft: true
      prerelease: true
      release: $(GitVersion_SemVer)
      on:
        branch: 
            - /release*/
    - provider: GitHub
      auth_token:
        secure: u7qaOQsrkLqq44yS24C0eM2vRCzp1A8gZTWNmlA58TIDJGmrDXguHL9H/vww7Fg/
      draft: true
      prerelease: false
      release: $(GitVersion_SemVer)
      on:
        branch: 
            - master
for:
-
  branches:
    only:
      - master
  on_success:
      - git config --global credential.helper store
      - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
      - git config --global user.email "aguacongas@gmail.com"
      - git config --global user.name "Aguacongas"
      - git checkout gh-pages
      - git stash
      - mkdir %GITVERSION_NuGetVersion%
      - move coverage\docs %GITVERSION_NuGetVersion%
      - git add %GITVERSION_NuGetVersion%
      - git commit %GITVERSION_NuGetVersion% -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%"
      - git push
-
  branches:
    except:
      - master
